create table AUTORES 
(
  NOMBRE VARCHAR (100) PRIMARY KEY ,
  NACIONALIDAD CHAR (50),
  COMENTARIOS CHAR (200)
  )
;

create table DIRECCIONES 
(
  CALLE VARCHAR (100) PRIMARY KEY,
  NUMERO VARCHAR (10),
  POBLACION VARCHAR (50),
  CP VARCHAR(10),
  PROVINCIA VARCHAR (30)
)
;

  
create table EDITORIALES
(
  NIF VARCHAR (20) PRIMARY KEY,
  NOMBRE VARCHAR (30),
  DIRECCION1 VARCHAR (100)
)
;
  
  
create table LIBROS
(
  ISBN VARCHAR (20) PRIMARY KEY,
  TITULO VARCHAR (40),
  EDITORIAL1 VARCHAR (30),
  AUTORES1 VARCHAR (100),
  ANO INTEGER,
  PRECIO DECIMAL (5,2),
  DESCRIPCION VARCHAR (200)
)
;
